name: MediFlow CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Cloud Function
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v1

      - name: Deploy Cloud Function
        run: |
          gcloud functions deploy appointment-checker \
            --gen2 \
            --runtime=python311 \
            --region=asia-south1 \
            --source=functions/appointment_checker \
            --entry-point=appointment_checker \
            --trigger-http \
            --no-allow-unauthenticated \
            --project=mediflow-solutions